# Generated by Django 5.0.3 on 2024-03-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Code_CIN', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('Adresse', models.CharField(max_length=30)),
                ('Date_of_creation', models.DateField()),
            ],
        ),
    ]
