# Generated by Django 5.0.3 on 2024-03-21 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('Id', models.IntegerField(default=5565, 
                                           primary_key=True, 
                                           serialize=False, 
                                           validators=[
                                               django.core.validators.MaxValueValidator(99999999), 
                                               django.core.validators.MinValueValidator(10000000)])),
                ('Amount', models.IntegerField(default='250', validators=[django.core.validators.MinValueValidator(251)])),
                ('Date_of_creation', models.DateField()),
            ],
        ),
    ]
